name: Siesta
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.

version: 1.0.0+5
#1.0.1+1
environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  flutter_animated_dialog: ^2.0.1
  image_picker: ^0.8.7+4
  flutter_switch: ^0.3.2
  readmore: ^2.2.0
  flutter_staggered_animations: ^1.1.1
  country_picker: ^2.0.20
  country_code_picker: ^3.0.0
  flutter_rating_bar: ^4.0.1
  dotted_line: ^3.1.0
  syncfusion_flutter_datepicker: ^21.2.3
  dotted_decoration: ^2.0.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  html_editor_enhanced: ^2.5.1
#  flutter_quill: ^6.4.4
#  provider: ^6.0.5
  http: ^0.13.0
  fluttertoast: ^8.2.2
  stacked: ^3.2.5
  circular_profile_avatar: ^2.0.5
  shared_preferences: ^2.1.1
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  flutter_widget_from_html: ^0.8.5
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.2

  firebase_core: ^2.15.0
  flutter_stripe: ^9.3.0
  url_launcher: ^6.1.5
  intl: ^0.18.1
  searchable_listview: ^2.5.1
  fast_cached_network_image: ^1.2.0
  flutter_pw_validator: ^1.6.0
  webview_flutter_plus: ^0.3.0+2
  jiffy: ^6.2.1
  csc_picker: ^0.2.7
#  record: ^5.0.4
  path_provider: ^2.1.1
  typewritertext: ^1.7.0
  flutter_bounceable: ^1.1.0
  just_audio: ^0.9.33
  blinking_text: ^1.0.2
  audio_video_progress_bar: ^0.9.0
  permission_handler: ^10.0.0
  country_state_city_pro: ^0.0.6

  another_audio_recorder: ^1.1.0
  audioplayers: ^5.2.1

  google_maps_flutter: ^2.5.3
  dropdown_button2: ^2.3.9
  dots_indicator: ^3.0.0
  chewie: ^1.7.5
  video_player: ^2.7.2
  video_thumbnail: ^0.5.3
  shimmer: ^3.0.0
  wechat_assets_picker: ^8.6.3
  dio: ^5.7.0
  qr_flutter: ^4.1.0
  clipboard: ^0.1.3
  app_links: ^3.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgFiles/
    - assets/pngFiles/
    - assets/audio_file/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito-Black
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf

    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf

    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf

    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf

    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf

    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf

    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
